routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'impersonate'], function()
{
    Route::get('/', function () {
        return view('auth.login');
    })->middleware('guest');

    Auth::routes();

    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('/users/impersonate/{user}', 'UsersController@impersonate');
    Route::get('/users/stop', 'UsersController@stopImpersonate');
    Route::resource('users', 'UsersController');

    Route::post('projects/report', ['as' => 'projects.report', 'uses' => 'ProjectsController@report']);
    Route::get('projects/{project}/toggle-closed', 'ProjectsController@toggleClosed')->name('projects.toggle');
    Route::get('projects/{project}/milestones', 'ProjectsController@getMilestones')->name('projects.milestones');
    Route::resource('projects', 'ProjectsController', ['except' => ['create', 'show']]);

    Route::post('tasks/toggle-completed/{task}', 'TasksController@toggleCompleted')->name('tasks.toggle');
    Route::resource('tasks', 'TasksController', ['except' => ['create', 'show']]);

    Route::post('milestones/{milestone}/toggle-achieved', 'MilestonesController@toggleAchieved')->name('milestone.toggle');
    Route::resource('milestones', 'MilestonesController', ['only' => ['store', 'update', 'destroy']]);

    Route::resource('statuses', 'StatusesController');

    Route::post('expirations/{expiration}/remove-attachment', 'ExpirationsController@removeAttachment')->name('expirations.attachment.remove');
    Route::post('expirations/{expiration}/add-attachment', 'ExpirationsController@addAttachment')->name('expirations.attachment.add');
    Route::get('expiratioins/{expiration}/download-attachment/{attachment}', 'ExpirationsController@downloadAttachment')->name('expirations.attachment.download');
    Route::get('expirations/calendar', 'ExpirationsController@calendar')->name('expirations.calendar');
    Route::resource('expirations', 'ExpirationsController');

    Route::get('teams/{team}/managers', 'TeamsController@teamManagersTable');
    Route::resource('teams', 'TeamsController');

    Route::resource('teams.specializations', 'TeamsSpecializationsController');

    Route::resource('users', 'UsersController', ['only' => ['index', 'store', 'edit', 'update', 'destroy']]);

    Route::post('roles', 'RolesController@createRole');

    Route::resource('comp-hours', 'CompHoursController');

    Route::get('announcements', 'AnnouncementsController@index');
    Route::post('announcements', 'AnnouncementsController@store');
    Route::post('announcements/{announcement}/read', 'AnnouncementsController@read');
    Route::post('announcements/{announcement}/hide', 'AnnouncementsController@hide');

    Route::get('reporting/staff', function() {
        return view('reporting.staff-hours');
    })->name('reporting.staff');

    Route::get('dropzone', function() {
       return view('vuetable');
    });

    /*
     *  API Routes
     */
    Route::group(['prefix' => 'api'] , function () {

        // Milestones API
        Route::get('milestones/{user}', 'MilestonesController@timeline');

        // ChartJS API Routes
        Route::group(['prefix' => 'charts'], function () {

            // Dashboard Charts
            Route::group(['prefix' => 'dashboard'], function () {
                Route::get('project-updates', 'Charts\DashboardController@projectUpdatesChart');
                Route::get('task-assignment', 'Charts\DashboardController@taskAssignmentChart');
                Route::get('staff-hours', 'Charts\DashboardController@staffHoursChart');
                Route::get('project-hours', 'Charts\DashboardController@projectHoursChart');
                Route::get('comp-hours', 'Charts\DashboardController@staffCompHoursChart');
            });

            // User Profile Charts
            Route::group(['prefix' => 'user-profile'], function () {
                Route::get('hours/this-week/{userId}', 'Charts\UserProfileController@statusUpdateHoursThisWeekChart');
                Route::get('hours/all-weeks/{userId}', 'Charts\UserProfileController@statusUpdateHoursAllWeeksChart');
                Route::get('tasks/{userId}', 'Charts\UserProfileController@taskAssignmentStatsChart');
            });

            //Reporting Page Charts
            Route::group(['prefix' => 'reporting'], function() {
                Route::get('staff/wtd', 'Charts\ReportingController@staffWtd');
                Route::get('staff/last7', 'Charts\ReportingController@staffLast7');
            });
        });

    });
});

resources/views/partials/_datatables.blade.php
<script type="text/javascript">
    $(document).ready(function() {
        $('#{{ $name }}').DataTable({
            pagingType: "full_numbers",
            order: [[ {{ $sort }}, "{{ $direction }}" ]],
            lengthMenu: [[5, 10, 25, 50, -1], [5, 10, 25, 50, "All"]],
            pageLength: {{ $pageLength or 10 }},
            responsive: true,   
            language: {
                search: "_INPUT_",
                searchPlaceholder: "Search records",
            }

        });


        var table = $('#{{ $name }}').DataTable();

        // Filter Tasks table based on current User
        var filterButton = $("#dataTablesFilterButton");
        var clearFilterButton = $("#dataTablesClearFilterButton");

        filterButton.on('click', function() {
            table.search("{{ Auth::user()->username }}").draw();
            filterButton.toggle();
            clearFilterButton.toggle();
        });

        clearFilterButton.on('click', function() {
            table.search("").draw();
            filterButton.toggle();
            clearFilterButton.toggle();
        });

        // Edit record
        table.on( 'click', '.edit', function () {
            $tr = $(this).closest('tr');

            var data = table.row($tr).data();
//                alert( 'You press on Row: ' + data[0] + ' ' + data[1] + ' ' + data[2] + '\'s row.' );
        } );

        // Delete a record
        table.on( 'click', '.remove', function (e) {
            $tr = $(this).closest('tr');
            table.row($tr).remove().draw();
            e.preventDefault();
        } );

        //Like record
        table.on( 'click', '.like', function () {
//            alert('You clicked on Like button');
        });
    });


    // Datatables in hidden panels need to be re-adjusted when shown
    $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
        $('#{{ $name }}').DataTable().columns.adjust().responsive.recalc();
    });

</script>

resources/views/partials/_datatables_server_side.blade.php
{{-- Datatables serverSide --}}
<script>
    var table = $('#{{ $name }}').DataTable({
        processing: true,
        serverSide: true,
        ajax: '{{ $api }}',
        info: false,
        bSort: false,
        fnDrawCallback: function() {
            $('.paginate_button').removeClass('paginate_button');
        }
    });


    var filterButton = $("#dataTablesFilterButton");
    var clearFilterButton = $("#dataTablesClearFilterButton");
    filterButton.on('click', function() {
        table.search("{{ Auth::user()->username }}").draw();
        filterButton.toggle();
        clearFilterButton.toggle();
    });
    clearFilterButton.on('click', function() {
        table.search("").draw();
        filterButton.toggle();
        clearFilterButton.toggle();
    });

</script>

resources/views/partials/_notifications.blade.php
<script>
    @if(Session::has('info'))
        $.notify({
        icon: 'pe-7s-bell',
        message: '{!! Session::get('info') !!}'
    },{
        type: 'info',
        timer: 4000
    });
    @endif
    @if(Session::has('success'))
        $.notify({
        icon: 'pe-7s-bell',
        message: '{!! Session::get('success') !!}'
    },{
        type: 'success',
        timer: 4000
    });
    @endif
    @if(Session::has('warning'))
        $.notify({
        icon: 'pe-7s-bell',
        message: '{!! Session::get('warning') !!}'
    },{
        type: 'warning',
        timer: 4000
    });
    @endif
    @if(Session::has('danger'))
        $.notify({
        icon: 'pe-7s-bell',
        message: '{!! Session::get('danger') !!}'
    },{
        type: 'danger',
        timer: 4000
    });
    @endif
</script>

resources/views/partials/_sidebar.blade.php
<div class="logo">
    <a href="{{ route('home') }}" class="logo-text">
        Project Insight
    </a>
</div>
<div class="logo logo-mini">
    <a href="/" class="logo-text">
        Pi
    </a>
</div>

<div class="sidebar-wrapper">
    <div class="user">
        <div class="photo">
            <img src="{{ Gravatar::src( Auth::user()->email ) }}" />
        </div>
        <div class="info">
            <a data-toggle="collapse" href="#collapseExample" class="collapsed">
                {{ Auth::user()->username }}
                <b class="caret"></b>
            </a>
            <div class="collapse" id="collapseExample">
                <ul class="nav">
                    <li><a href="{{ route('users.edit', ['id' => Auth::user()->id]) }}">My Profile</a></li>
                </ul>
            </div>
        </div>
    </div>

    <ul class="nav">
        <li @if(in_array(Route::current()->getName(), ['home'])) class="active" @endif>
            <a href="{{ route('home') }}">
                <i class="pe-7s-graph"></i>
                <p>Dashboard</p>
            </a>
        </li>
        <li @if(in_array(Route::current()->getName(), ['projects.index', 'projects.edit'])) class="active" @endif>
            <a href="{{ route('projects.index') }}">
                <i class="pe-7s-note2"></i>
                <p>Projects</p>
            </a>
        </li>
        <li @if(in_array(Route::current()->getName(), ['tasks.index', 'tasks.edit'])) class="active" @endif>
            <a href="{{ route('tasks.index') }}">
                <i class="fa fa-tasks-o" aria-hidden="true"></i>
                <p>Tasks</p>
            </a>
        </li>
        <li @if(in_array(Route::current()->getName(), ['expirations.index', 'expirations.calendar'])) class="active" @endif>
            <a data-toggle="collapse" href="#expirations" area-expanded="true" aria-expanded="false" class="collapsed">
                <i class="pe-7s-timer"></i>
                <p>System Expirations
                    <b class="caret"></b>
                </p>
            </a>
            <div @if(in_array(Route::current()->getName(), ['expirations.index', 'expirations.calendar'])) class="collapse" id="expirations" @else class="collapse" id="expirations" aria-expanded="false" @endif>
                <ul class="nav">
                    <li><a href="{{ route('expirations.index') }}">List</a></li>
                </ul>
                <ul class="nav">
                    <li><a href="{{ route('expirations.calendar') }}">Calendar</a></li>
                </ul>
            </div>
        </li>
        @if(Auth::user()->hasRole('admin') || Auth::user()->hasRole('manager'))
        <li @if(in_array(Route::current()->getName(), ['reporting.staff'])) class="active" @endif>
            <a data-toggle="collapse" href="#staffReporting" area-expanded="true" aria-expanded="false" class="collapsed">
                <i class="pe-7s-graph2"></i>
                <p>Reporting
                    <b class="caret"></b>
                </p>
            </a>
            <div @if(in_array(Route::current()->getName(), ['reporting.staff'])) class="collapse" id="staffReporting" @else class="collapse" id="staffReporting" aria-expanded="false" @endif>
                <ul class="nav">
                    <li><a href="{{ route('reporting.staff') }}">My Staff</a></li>
                </ul>
            </div>
        </li>
        @endif
        @if(Auth::user()->hasRole('admin') || Auth::user()->hasRole('manager'))
        <li @if(in_array(Route::current()->getName(), ['teams.index', 'teams.edit'])) class="active" @endif>
            <a href="{{ route('teams.index') }}">
                <i class="pe-7s-users"></i>
                <p>Teams</p>
            </a>
        </li>
        <li @if(in_array(Route::current()->getName(), ['users.index', 'users.edit'])) class="active" @endif>
            <a href="{{ route('users.index') }}">
                <i class="pe-7s-id"></i>
                <p>Users</p>
            </a>
        </li>
        @endif
        @if(Auth::user()->isImpersonating())
        <li class="fa-blink">
            <a href="{{ url('users/stop') }}">
                <i class="fa fa-user-secret" aria-hidden="true"></i>
                <p>Stop Impersonating</p>
            </a>
        </li>
        @endif
    </ul>
</div>

resources/views/partials/_timeline.blade.php
<script src="https://cdnjs.cloudflare.com/ajax/libs/vis/4.16.1/vis.js"></script>
<script type="text/javascript">
    var items;
    // DOM element where the Timeline will be attached
    var container = document.getElementById('visualization');
    // Create a DataSet (allows two way data-binding)
    $.ajax({
        url: "/api/milestones/{{ Auth::user()->id }}",
        cache: false,
        success: function(data){
            buildTimeline(data);
        }
    });
    function buildTimeline(data) {
        var timelineData = JSON.parse(data);
        items = new vis.DataSet(timelineData);

        // Configuration for the Timeline
        var options = {
            clickToUse: true,
            start: '{{ Carbon\Carbon::now()->subMonth()->toDateString() }}',
            end: '{{ Carbon\Carbon::now()->addMonths(2)->toDateString() }}',  // end is optional
        };

        // Create a Timeline
        var timeline = new vis.Timeline(container, items, options);
    }
</script>

resources/views/partials/_top_nav.blade.php
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-minimize">
            <button id="minimizeSidebar" class="btn btn-warning btn-fill btn-round btn-icon">
                <i class="fa fa-ellipsis-v visible-on-sidebar-regular"></i>
                <i class="fa fa-navicon visible-on-sidebar-mini"></i>
            </button>
        </div>
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#"></a>
        </div>
        <div class="collapse navbar-collapse">

            <ul class="nav navbar-nav navbar-right">

                <annoucements can-add-announcements="{{ Auth::user()->hasRole('admin') || Auth::user()->hasRole('manager') }}"></annoucements>

                <li class="dropdown dropdown-with-icons">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-list"></i>
                        <p class="hidden-md hidden-lg">
                            More
                            <b class="caret"></b>
                        </p>
                    </a>
                    <ul class="dropdown-menu dropdown-with-icons">
                        <li>
                            <a href="{{ url('/logout') }}"
                               class="text-danger"
                               onclick="event.preventDefault();
                                                document.getElementById('logout-form').submit();">
                                <i class="pe-7s-close-circle"></i>
                                Log out
                            </a>
                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                {{ csrf_field() }}
                            </form>
                        </li>
                    </ul>
                </li>

            </ul>
        </div>
    </div>
</nav>