routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'impersonate'], function()
{
    Route::get('/', function () {
        return view('auth.login');
    })->middleware('guest');

    Auth::routes();

    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('/users/impersonate/{user}', 'UsersController@impersonate');
    Route::get('/users/stop', 'UsersController@stopImpersonate');
    Route::resource('users', 'UsersController');

    Route::post('projects/report', ['as' => 'projects.report', 'uses' => 'ProjectsController@report']);
    Route::get('projects/{project}/toggle-closed', 'ProjectsController@toggleClosed')->name('projects.toggle');
    Route::get('projects/{project}/milestones', 'ProjectsController@getMilestones')->name('projects.milestones');
    Route::resource('projects', 'ProjectsController', ['except' => ['create', 'show']]);

    Route::post('tasks/toggle-completed/{task}', 'TasksController@toggleCompleted')->name('tasks.toggle');
    Route::resource('tasks', 'TasksController', ['except' => ['create', 'show']]);

    Route::post('milestones/{milestone}/toggle-achieved', 'MilestonesController@toggleAchieved')->name('milestone.toggle');
    Route::resource('milestones', 'MilestonesController', ['only' => ['store', 'update', 'destroy']]);

    Route::resource('statuses', 'StatusesController');

    Route::post('expirations/{expiration}/remove-attachment', 'ExpirationsController@removeAttachment')->name('expirations.attachment.remove');
    Route::post('expirations/{expiration}/add-attachment', 'ExpirationsController@addAttachment')->name('expirations.attachment.add');
    Route::get('expiratioins/{expiration}/download-attachment/{attachment}', 'ExpirationsController@downloadAttachment')->name('expirations.attachment.download');
    Route::get('expirations/calendar', 'ExpirationsController@calendar')->name('expirations.calendar');
    Route::resource('expirations', 'ExpirationsController');

    Route::get('teams/{team}/managers', 'TeamsController@teamManagersTable');
    Route::resource('teams', 'TeamsController');

    Route::resource('teams.specializations', 'TeamsSpecializationsController');

    Route::resource('users', 'UsersController', ['only' => ['index', 'store', 'edit', 'update', 'destroy']]);

    Route::post('roles', 'RolesController@createRole');

    Route::resource('comp-hours', 'CompHoursController');

    Route::get('announcements', 'AnnouncementsController@index');
    Route::post('announcements', 'AnnouncementsController@store');
    Route::post('announcements/{announcement}/read', 'AnnouncementsController@read');
    Route::post('announcements/{announcement}/hide', 'AnnouncementsController@hide');

    Route::get('reporting/staff', function() {
        return view('reporting.staff-hours');
    })->name('reporting.staff');

    Route::get('dropzone', function() {
       return view('vuetable');
    });

    /*
     *  API Routes
     */
    Route::group(['prefix' => 'api'] , function () {

        // Milestones API
        Route::get('milestones/{user}', 'MilestonesController@timeline');

        // ChartJS API Routes
        Route::group(['prefix' => 'charts'], function () {

            // Dashboard Charts
            Route::group(['prefix' => 'dashboard'], function () {
                Route::get('project-updates', 'Charts\DashboardController@projectUpdatesChart');
                Route::get('task-assignment', 'Charts\DashboardController@taskAssignmentChart');
                Route::get('staff-hours', 'Charts\DashboardController@staffHoursChart');
                Route::get('project-hours', 'Charts\DashboardController@projectHoursChart');
                Route::get('comp-hours', 'Charts\DashboardController@staffCompHoursChart');
            });

            // User Profile Charts
            Route::group(['prefix' => 'user-profile'], function () {
                Route::get('hours/this-week/{userId}', 'Charts\UserProfileController@statusUpdateHoursThisWeekChart');
                Route::get('hours/all-weeks/{userId}', 'Charts\UserProfileController@statusUpdateHoursAllWeeksChart');
                Route::get('tasks/{userId}', 'Charts\UserProfileController@taskAssignmentStatsChart');
            });

            //Reporting Page Charts
            Route::group(['prefix' => 'reporting'], function() {
                Route::get('staff/wtd', 'Charts\ReportingController@staffWtd');
                Route::get('staff/last7', 'Charts\ReportingController@staffLast7');
            });
        });

    });
});

app/Models/Task.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Riesjart\VueTable\Traits\VueTableSortable;

class Task extends Model
{
    use VueTableSortable;

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'description', 'completed', 'project_id', 'assigned_to', 'created_by'
    ];

    /**
     * A Task belongs to a Project
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function project()
    {
        return $this->belongsTo(Project::class);
    }

    /**
     * A Task has many Statuses
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function statuses()
    {
        return $this->hasMany(Status::class);
    }

    /**
     * A Task is owned by a User
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function owner()
    {
        return $this->belongsTo(User::class, 'assigned_to');
    }
}

app/Http/Controllers/TasksController.php
<?php

namespace App\Http\Controllers;

use App\Models\Task;
use Illuminate\Http\Request;

class TasksController extends Controller
{

    /**
     * Create a new controller instance.
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        // Tasks vuetable-2 AJAX Request
        if (request()->ajax()) {

            if(\Auth::user()->hasRole('manager')) {
                if(filter_var($request->input('showCompleted'), FILTER_VALIDATE_BOOLEAN)) {
                    $query = Task::with(['owner', 'project'])
                        ->whereHas('project', function($q) {
                            $q->whereIn('team_id', \Auth::user()->managedTeams->pluck('id')->toArray());
                        })
                        ->orderByVueTable();
                } else {
                    $query = Task::with(['owner', 'project'])
                        ->whereHas('project', function($q) {
                            $q->whereIn('team_id', \Auth::user()->managedTeams->pluck('id')->toArray());
                        })
                        ->where('completed', 0)
                        ->orderByVueTable();
                }

            } else {
                if(filter_var($request->input('showCompleted'), FILTER_VALIDATE_BOOLEAN)) {
                    $query = Task::with(['owner', 'project'])
                        ->whereIn('project_id', \Auth::user()->team->projects->pluck('id')->toArray())
                        ->orderByVueTable();
                } else {
                    $query = Task::with(['owner', 'project'])
                        ->whereIn('project_id', \Auth::user()->team->projects->pluck('id')->toArray())
                        ->where('completed', 0)
                        ->orderByVueTable();
                }
            }

            if ($request->exists('filter')) {
                $query->where(function ($q) use ($request) {
                    $value = "%{$request->filter}%";
                    $q->where('name', 'like', $value)
                        ->orWhere('description', 'like', $value)
                        ->orWhereHas('owner', function($query) use ($value) {
                            $query->where('username', 'like', $value);
                        })
                        ->orWhereHas('project', function($query) use ($value) {
                            $query->where('name', 'like', $value);
                        })
                        ->orWhere('created_at', 'like', $value);
                });
            }
            return response()->json(
                $query->paginate(10)
            );
        }

        return view('tasks.index');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // Validate the form request
        $this->validate($request, ['name' => 'required', 'assigned_to' => 'required', 'created_by' => 'required', 'project_id' => 'required']);

        try {
            $task = Task::create($request->all());
        } catch (\PDOException $e) {
            \Log::error('App\Models\Task PDOException', [$e->getMessage()]);
            $request->session()->flash('danger', 'Sorry, something went wrong saving that information!');
            return response()->json();
        }

        // Fire TaskWasCreated Event
//        Event::fire(new TaskWasCreated($task));

        $request->session()->flash('success', 'Task Added!');
        return response()->json();
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Task $task
     * @return \Illuminate\Http\Response
     */
    public function edit(Task $task)
    {
        if(request()->ajax()) {
            return \DB::table('statuses')
                ->join('users', 'statuses.user_id', 'users.id')
                ->select(
                    'statuses.id',
                    'statuses.title',
                    'statuses.body',
                    'users.username',
                    'users.email',
                    'statuses.hours_spent',
                    'statuses.admin_time',
                    'statuses.performed_at',
                    'statuses.created_at'
                )
                ->where('statuses.task_id', $task->id)
                ->orderBy('statuses.created_at', 'desc')
                ->get();
        }
        return view('tasks.edit', compact('task'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param Task $task
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Task $task)
    {
        $this->validate($request, ['name' => 'required', 'assigned_to' => 'required']);

        $task->update($request->all());

        return redirect()->back()->with('success', 'Task Updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Task $task
     * @return \Illuminate\Http\Response
     */
    public function destroy(Task $task)
    {
        $task->delete();
        return response()->json();
    }

    /**
     * Toggle Task completed status
     *
     * @param Task $task
     * @return \Illuminate\Http\Response
     */
    public function toggleCompleted(Task $task)
    {
        $task->completed = !$task->completed;
        $task->save();

        return response()->json();
    }
}

resources/views/tasks/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <ol class="breadcrumb">
                        <li><a href="{{ route('home') }}">Home</a></li>
                        <li><a href="{{ route('projects.index') }}">Projects</a></li>
                        <li><a href="{{ route('projects.edit', ['project' => $task->project->id]) }}">{{ $task->project->name }}</a></li>
                        <li class="active">{{ $task->name }}</li>
                    </ol>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <div class="card">
                        <div class="header">
                            Edit Task
                        </div>
                        <div class="content">
                            {!! Form::model( $task, ['method' => 'PUT', 'id' => 'editTaskForm', 'route' => ['tasks.update', $task->id]]) !!}
                            <div class="form-group">
                                {!! Form::label('name', 'Name', ['class' => 'col-sm-3 control-label']) !!}
                                {!! Form::text('name', null, ['class' => 'form-control', 'id' => 'task_name']) !!}
                            </div>
                            <div class="form-group">
                                {!! Form::label('description', 'Description', ['class' => 'col-sm-3 control-label']) !!}
                                {!! Form::textarea('description', null, ['class' => 'form-control', 'id' => 'task_description']) !!}
                            </div>
                            <div class="form-group">
                                {!! Form::label('assigned_to', 'Assignment', ['class' => 'col-sm-3 control-label']) !!}
                                {!! Form::select('assigned_to', $task->project->team->members->pluck('username', 'id'), null, ['class' => 'form-control selectpicker', 'data-style' => 'btn-info btn-fill btn-block', 'data-menu-style' => 'dropdown-blue', 'data-title' => 'Select Assignment', 'id' => 'task_selected_user_id']) !!}
                            </div>
                            {!! Form::submit('Update', ['class' => 'btn btn-wd btn-info']) !!}
                            {!! Form::close() !!}
                        </div>
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="card">
                        <div class="header">
                        </div>
                        <div class="content">
                            <pi-status-timeline :task="{{ $task->toJson() }}" :user="{{ Auth::user()->toJson() }}"></pi-status-timeline>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('scripts')


@endsection

resources/views/tasks/index.blade.php
@extends('layouts.app')

@section('content')

    <tasks-table></tasks-table>

@endsection

@section('scripts')

@endsection